# Generated by Django 5.1.7 on 2025-03-18 05:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('chunk_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=512)),
                ('chunk_text', models.TextField()),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'chunks',
                'indexes': [models.Index(fields=['file_name'], name='chunks_file_na_068bc5_idx')],
            },
        ),
    ]
